export const commentRegex: Record<string, string> = {
  default: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  // abap: '',
  // bat: '',
  // bibtex: '',
  // clojure: '',
  coffeescript: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  c: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  cpp: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  csharp: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  css: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  dockerfile: '#',
  // fsharp: '',
  // 'git-commit': '',
  // 'git-rebase': '',
  // go: '',
  // groovy: '',
  // handlebars: '',
  // haml: '',
  html: '<!--(.*?)(-->)?',
  // ini: '',
  java: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  javascript: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  javascriptreact: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  jsx: '<!--(.*?)(-->)?',
  json: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  jsonc: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  // latex: '',
  less: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  // lua: '',
  // makefile: '',
  // markdown: '',
  'objective-c': '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  'objective-cpp': '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  // perl: '',
  // perl6: '',
  php: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  // plaintext: '',
  // powershell: '',
  // jade: '',
  // pug: '',
  python: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  // r: '',
  // razor: '',
  ruby: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  // rust: '',
  scss: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  sass: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  // shaderlab: '',
  // shellscript: '',
  // slim: '',
  sql: '(--.*|#.*)',
  stylus: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  // swift: '',
  typescript: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  typescriptreact: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  // tex: '',
  // vb: '',
  vue: '(//.*|/\\*(.*?)(\\*/)?|\\*(.*?)(\\*/)?)',
  'vue-html': '<!--(.*?)(-->)?',
  xml: '<!--(.*?)(-->)?',
  // xsl: '',
  yaml: '#.*',
};

export const commentMarkers: Record<string, { start: string; end: string }[]> = {
  default: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  // abap: [],
  // bat: [],
  // bibtex: [],
  // clojure: [],
  coffeescript: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  c: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  cpp: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  csharp: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  css: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  dockerfile: [{ start: '#', end: '(?=\\n)' }],
  // fsharp: [],
  // 'git-commit': [],
  // 'git-rebase': [],
  // go: [],
  // groovy: [],
  // handlebars: [],
  // haml: [],
  html: [{ start: '<!--(.*?)(-->)?', end: '-->' }],
  // ini: [],
  java: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  javascript: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  javascriptreact: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  jsx: [{ start: '<!--(.*?)(-->)?', end: '-->' }],
  json: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  jsonc: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  // latex: [],
  less: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  // lua: [],
  // makefile: [],
  // markdown: [],
  'objective-c': [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  'objective-cpp': [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  // perl: [],
  // perl6: [],
  php: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  // plaintext: [],
  // powershell: [],
  // jade: [],
  // pug: [],
  python: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  // r: [],
  // razor: [],
  ruby: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  // rust: [],
  scss: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  sass: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  // shaderlab: [],
  // shellscript: [],
  // slim: [],
  sql: [
    { start: '#', end: '(?=\\n)' },
    { start: '--', end: '(?=\\n)' },
  ],
  stylus: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  // swift: [],
  typescript: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  typescriptreact: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  // tex: [],
  // vb: [],
  vue: [
    { start: '//', end: '(?=\\n)' },
    { start: '/\\*', end: '\\*/' },
  ],
  'vue-html': [{ start: '<!--(.*?)(-->)?', end: '-->' }],
  xml: [{ start: '<!--(.*?)(-->)?', end: '-->' }],
  // xsl: [],
  yaml: [{ start: '#', end: '(?=\\n)' }],
};
