/* eslint-disable @typescript-eslint/naming-convention */
import { TextBlockDefinition } from "../providers/StringProcessingProvider";

export const decoratorRegex: Record<string, string> = {
  default: "",
  // abap: '',
  // bat: '',
  // bibtex: '',
  // clojure: '',
  // coffeescript: '',
  // c: '',
  // cpp: '',
  // csharp: '',
  // css: '',
  // dockerfile: '',
  // fsharp: '',
  // '',
  // '',
  // go: '',
  // groovy: '',
  // handlebars: '',
  // haml: '',
  // html: '',
  // ini: '',
  java: "@",
  javascript: "@",
  javascriptreact: "@",
  jsx: "@",
  // json: '',
  // jsonc: '',
  // latex: '',
  // less: '',
  // lua: '',
  // makefile: '',
  // markdown: '',
  // 'objective-c': '',
  // 'objective-cpp': '',
  // perl: '',
  // perl6: '',
  // php: '',
  // plaintext: '',
  // powershell: '',
  // jade: '',
  // pug: '',
  python: "@",
  // r: '',
  // razor: '',
  // ruby: '',
  // rust: '',
  // scss: '',
  // sass: '',
  // shaderlab: '',
  // shellscript: '',
  // slim: '',
  // sql: '',
  // stylus: '',
  // swift: '',
  typescript: "@",
  typescriptreact: "@",
  // tex: '',
  // vb: '',
  vue: "@",
  // 'vue-html': '',
  // xml: '',
  // xsl: '',
  // yaml: '',
};

export const decoratorMarkers: Record<string, TextBlockDefinition[]> = {
  default: [],
  // abap: [],
  // bat: [],
  // bibtex: [],
  // clojure: [],
  // coffeescript: [],
  // c: [],
  // cpp: [],
  // csharp: [],
  // css: [],
  // dockerfile: [],
  // fsharp: [],
  // [],
  // [],
  // go: [],
  // groovy: [],
  // handlebars: [],
  // haml: [],
  // html: [],
  // ini: [],
  java: [{ start: "^\\s*@" }],
  javascript: [{ start: "^\\s*@" }],
  javascriptreact: [{ start: "^\\s*@" }],
  jsx: [{ start: "^\\s*@" }],
  // json: [],
  // jsonc: [],
  // latex: [],
  // less: [],
  // lua: [],
  // makefile: [],
  // markdown: [],
  // 'objective-c': [],
  // 'objective-cpp': [],
  // perl: [],
  // perl6: [],
  // php: [],
  // plaintext: [],
  // powershell: [],
  // jade: [],
  // pug: [],
  python: [{ start: "^\\s*@" }],
  // r: [],
  // razor: [],
  // ruby: [],
  // rust: [],
  // scss: [],
  // sass: [],
  // shaderlab: [],
  // shellscript: [],
  // slim: [],
  // sql: [],
  // stylus: [],
  // swift: [],
  typescript: [{ start: "^\\s*@" }],
  typescriptreact: [{ start: "^\\s*@" }],
  // tex: [],
  // vb: [],
  vue: [{ start: "^\\s*@" }],
  // 'vue-html': [],
  // xml: [],
  // xsl: [],
  // yaml: [],
};
